apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
