apiVersion: v1
kind: Service
metadata:
  name: {{ include "lms.fullname" . }}-backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.backend.containerPort }}
