apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lms.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://{{ include "lms.fullname" . }}-backend:{{ .Values.service.backendPort }}"
