apiVersion: v1
kind: Service
metadata:
  name: {{ include "lms.fullname" . }}-frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.frontend.containerPort }}
