apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lms.fullname" . }}-db-migrate
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: {{ .Values.database.secretName }}
