apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DATABASE_URL: mysql://username:password@your-rds-endpoint:3306/vicky_nextjs
  NEXTAUTH_SECRET: 12D16C923BA17672F89B18C1DB22A
