apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DATABASE_URL: mysql://vickytronicuser:Vignesh123!@vickytronic-site-mysql.cy3g00wiie5h.us-east-1.rds.amazonaws.com:3306/vickytronicdb
  NEXTAUTH_SECRET: 12D16C923BA17672F89B18C1DB22A
